/* config.h. Generated by cmake from config.h.cmake */

/* The size of a `int', as computed by sizeof. */
#define SIZEOF_INT ${SIZEOF_INT}

/* The size of a `long', as computed by sizeof. */
#define SIZEOF_LONG ${SIZEOF_LONG}

/* Building on Windows */
#cmakedefine WIN32 1

/* Package name */
#define PACKAGE "${PROJECT_NAME}"
#define VERSION "${REL}"
#define PATCH "${${PROJECT_NAME}_PATCH_LEVEL}"
