//
//  Copyright (C) 2010  Nick Gasson
//
//  This program is free software: you can redistribute it and/or modify
//  it under the terms of the GNU General Public License as published by
//  the Free Software Foundation, either version 3 of the License, or
//  (at your option) any later version.
//
//  This program is distributed in the hope that it will be useful,
//  but WITHOUT ANY WARRANTY; without even the implied warranty of
//  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
//  GNU General Public License for more details.
//
//  You should have received a copy of the GNU General Public License
//  along with this program.  If not, see <http://www.gnu.org/licenses/>.
//

#include "IScenery.hpp"

// Trees generated by L-systems
class LTree : public IScenery {
public:
   LTree();

   // IScenery interface
   void render() const;
   void setPosition(float x, float y, float z);
private:
};

LTree::LTree()
{

}

void LTree::render() const
{

}

void LTree::setPosition(float x, float y, float z)
{

}

ISceneryPtr makeLTree()
{
   return ISceneryPtr(new LTree);
}


